### ISSUE TITLE
Script no longer working

### ISSUE THREAD

**Issue by superskaterxes** [micro2112/Lowes2019#2]
i no longer see the check prices box above the item and when running manually via chrome extension bar the search box never has any results.

**Comment by micro2112** [comment]
Thank you for reaching out. Lowes recently updated their site, and I have been looking into a fix. Please try todays update and let me know.

**Comment by kristy1988** [comment]
I love love this script but yesterday it seemed to stop working for the 1st time since the June 2nd update. I would love to donate money for this script to be fixed ! i assume lots of new issues will arise as Lowe's keeps tweaking their new 2020 website. I appreciate everyone who has worked on this in the past present and future as I know its a lot of work but it is greatly appreciated !!!

**Comment by micro2112** [comment]
Can you elaborate on what is not working? I have some reporting that it is not searching all of the stores selected, is that the same issue you are having?

**Comment by kristy1988** [comment]
Yes, same not searching at all .Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: micro2112 <notifications@github.com> Date: 8/11/20  1:36 PM  (GMT-05:00) To: micro2112/Lowes2019 <Lowes2019@noreply.github.com> Cc: kristy1988 <kristyrjohnson88@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [micro2112/Lowes2019] Script no longer working (#2) 
Can you elaborate on what is not working? I have some reporting that it is not searching all of the stores selected, is that the same issue you are having?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/micro2112/Lowes2019/issues/2#issuecomment-672123512",
"url": "https://github.com/micro2112/Lowes2019/issues/2#issuecomment-672123512",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by micro2112** [comment]
Can you give me some info on your system? 

Everything seems to be working on my system.  I am testing a fix for the timeout issue right now, but it is still working overall.

**Comment by boosted0ne** [comment]
Mine was not working at all.  Tested today and it seems to be working now. 



On Tuesday, August 11, 2020, 3:10 PM, micro2112 <notifications@github.com> wrote:




Can you give me some info on your system?

Everything seems to be working on my system. I am testing a fix for the timeout issue right now, but it is still working overall.

**Comment by micro2112** [comment]
I pushed a new update with option to slow down searches if you start getting blocked.
Please test that one as well. 

I will wait for @kristy1988  to reply before closing this, but will close yours @boosted0ne .
